# Generated by Django 5.2.6 on 2025-09-09 09:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('sepatu bola', 'Sepatu Bola'), ('jersey', 'Jersey'), ('bola', 'Bola'), ('aksesoris', 'Aksesoris'), ('alat latihan', 'Alat Latihan')], default='update', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('stok', models.IntegerField(default=0)),
            ],
        ),
    ]
