# Generated by Django 5.2.6 on 2025-09-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_news_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sepatu bola', 'Sepatu Bola'), ('jersey', 'Jersey'), ('bola', 'Bola'), ('aksesoris', 'Aksesoris'), ('alat latihan', 'Alat Latihan')], default='sepatu bola', max_length=20),
        ),
    ]
